import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { mkdir,rm } from 'node:fs/promises';
await mkdir(new URL('../node_modules/.cache/',import.meta.url),{recursive:true});
const file = new URL('../node_modules/.cache/email-worker.mjs',import.meta.url).pathname;
await build({entryPoints:[new URL('../supabase/functions/notify-club/index.ts',import.meta.url).pathname],outfile:file,format:'esm',platform:'node'});
const config={WEBHOOK_SECRET:'test-secret',SUPABASE_URL:'https://db.example.test',SUPABASE_SERVICE_ROLE_KEY:'server-only',RESEND_API_KEY:'email-only',MAIL_FROM:'Club <club@example.test>'};
globalThis.Deno={env:{get:key=>config[key]},serve(){}};
const {handle}=await import(file);
const calls=[];
const job={job_id:'uuid-job',token:'uuid-token',kind:'chat',ride_id:'ride1',recipient_id:'member',email:'private@example.test',name:'<Miguel>',title:'Ruta <prueba>',starts_at:'2099-10-04T06:30:00Z',meeting_point:'Parque'};
globalThis.fetch=async(url,options)=>{calls.push({url,options});if(url.includes('/rpc/'))return new Response(JSON.stringify([job]));return new Response('',{status:200})};
const request=secret=>new Request('https://worker.example.test',{method:'POST',headers:{'x-webhook-secret':secret}});
assert.equal((await handle(request('wrong'))).status,401);assert.equal(calls.length,0);
delete config.RESEND_API_KEY;assert.equal((await handle(request('test-secret'))).status,503);assert.equal(calls.length,0);config.RESEND_API_KEY='email-only';
const result=await handle(request('test-secret'));assert.deepEqual(await result.json(),{sent:1,failed:0});
const mail=calls.find(c=>c.url.includes('api.resend.com'));
assert.deepEqual(JSON.parse(mail.options.body).to,['private@example.test']);
assert.equal(mail.options.headers['Idempotency-Key'],'cdh-notice-uuid-job');
assert.ok(JSON.parse(mail.options.body).html.includes('&lt;prueba&gt;'));
assert.ok(calls.some(c=>c.options.method==='PATCH' && JSON.parse(c.options.body).state==='sent' && c.url.includes('lease_token=eq.uuid-token')));
calls.length=0;
globalThis.fetch=async(url,options)=>{calls.push({url,options});if(url.includes('/rpc/'))return new Response(JSON.stringify([job]));if(url.includes('api.resend.com'))return new Response('',{status:429});return new Response('',{status:200})};
assert.deepEqual(await (await handle(request('test-secret'))).json(),{sent:0,failed:1});
assert.ok(calls.some(c=>c.options.method==='PATCH' && JSON.parse(c.options.body).state==='pending'));
await rm(file);console.log('Worker correo: autenticación, configuración, privacidad, idempotencia y reintento superados (sin enviar correos reales).');
